### ISSUE TITLE
Assertion Error -- AUR dduper-git

### ISSUE THREAD

**Issue by KenJyn76** [Lakshmipathi/dduper#45]
Using dduper-git or dduper-bin on Arch, I'm running into the following error. I'm not sure what other informaction to give, but if you need more, let me know. I'm sure I just missed a setup step, or something similar.

```
Traceback (most recent call last):
  File "/usr/bin/dduper", line 576, in <module>
    main(results)
  File "/usr/bin/dduper", line 466, in main
    dedupe_dir(results.dir_path, results.dry_run, results.recurse)
  File "/usr/bin/dduper", line 457, in dedupe_dir
    dedupe_files(file_list, dry_run)
  File "/usr/bin/dduper", line 411, in dedupe_files
    ret = do_dedupe(src_file, dst_file, dry_run)
  File "/usr/bin/dduper", line 225, in do_dedupe
    assert len(out1) != 0
AssertionError
```

**Comment by KenJyn76** [comment]
UPDATE: I've now tried installing via all three methods outlined in the installation instructions, meeting the same error. In addition, I've tried multiple filesystems, and multiple systems. I can't seem to get this to work.

**Comment by Lakshmipathi** [comment]
can you provide me the exact command ? Are you running this on a subvolume?

**Comment by KenJyn76** [comment]
I have run multiple commands -- most commonly, though

dduper -p /dev/sda -d /home -r --analyze

I've been running it on directories where subvolumes are mounted.

**Comment by Lakshmipathi** [comment]
> I've been running it on directories where subvolumes are mounted.

I think thats the issue. I have fix for running dduper on subvolume - I hope to merge those changes this week. 
If you run dduper on your top-level subvolume (id 5) it will work and it will fail on subvolume with ids >= 256

**Comment by jmphilippe** [comment]
Hello, I think I'm facing the same issue:

`# dduper --device /dev/sda1 --dir /data/share/ --recurse --analyze
Traceback (most recent call last):
  File "/usr/sbin/dduper", line 715, in <module>
    main(results)
  File "/usr/sbin/dduper", line 595, in main
    dedupe_dir(results.dir_path, results.dry_run, results.recurse)
  File "/usr/sbin/dduper", line 578, in dedupe_dir
    dedupe_files(f, dry_run)
  File "/usr/sbin/dduper", line 482, in dedupe_files
    ret = do_dedupe(src_file, dst_file, dry_run)
  File "/usr/sbin/dduper", line 293, in do_dedupe
    assert len(out1) != 0
AssertionError
`
It seems to be working if subvolume id = 256 but failing at id=257. Have you finally released some patch code, at least for testing?

**Comment by bugsyb** [comment]
Checking on here too re subvolumes, as seems like plenty of Issues are open due to this and fix might be already done, just not pushed put to master.
