### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by symphorien** [Lakshmipathi/dduper#57]
```
$ dduper --device /dev/mapper/vg-root --dir /nix/store/*llvm*-lib --recurse
[...]
Dedupe completed for /nix/store/1xcwdxx002a70ml4h1k0byciidbsnx2n-llvm-8.0.1-lib/lib/libLLVM-8.so:/nix/store/hpa2wxp7cjxgb5bn44wnhb4aig65s1kg-llvm-8.0.1-lib/lib/libLLVM.so
Summary
blk_size : 4KB  chunksize : 128KB
/nix/store/1xcwdxx002a70ml4h1k0byciidbsnx2n-llvm-8.0.1-lib/lib/libLLVM-8.so has 646 chunks
/nix/store/hpa2wxp7cjxgb5bn44wnhb4aig65s1kg-llvm-8.0.1-lib/lib/libLLVM.so has 643 chunks
Matched chunks: 1
Unmatched chunks: 642
Total size(KB) deduped: 128
************************
error([Errno 22] Invalid argument)
Traceback (most recent call last):
  File "/nix/store/ldmj09d7pfyircf1j34m8rhpy0qxlj2l-dduper-v0.04/bin//dduper", line 594, in <module>
    main(results)
  File "/nix/store/ldmj09d7pfyircf1j34m8rhpy0qxlj2l-dduper-v0.04/bin//dduper", line 465, in main
    dedupe_dir(results.dir_path, results.dry_run, results.recurse)
  File "/nix/store/ldmj09d7pfyircf1j34m8rhpy0qxlj2l-dduper-v0.04/bin//dduper", line 456, in dedupe_dir
    dedupe_files(file_list, dry_run)
  File "/nix/store/ldmj09d7pfyircf1j34m8rhpy0qxlj2l-dduper-v0.04/bin//dduper", line 410, in dedupe_files
    ret = do_dedupe(src_file, dst_file, dry_run)
  File "/nix/store/ldmj09d7pfyircf1j34m8rhpy0qxlj2l-dduper-v0.04/bin//dduper", line 281, in do_dedupe
    bytes_deduped,status = ioctl_fideduperange(src_fd, s)
TypeError: cannot unpack non-iterable NoneType object
```

**Comment by Lakshmipathi** [comment]
Could you please try with `--dir /nix/store/` instead of  `--dir /nix/store/*llvm*-lib` ? Let me know if you still face this issue.

**Comment by symphorien** [comment]
Well it takes infinite time without crashing because this folder contains millions of files and dduper is quadratic(!).
