### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by GfEW** [Lakshmipathi/dduper#68]
The UnicodeEncodeError reported by @plattrap in issue #15 has been marked "resolved" long ago, but I've just started using dduper yesterday (pre-built binary 0.04) and already get that:

```
dduper --device /dev/sdd2 --recurse --dir /btrfstestdir
  File "/usr/sbin/dduper", line 734, in <module>
    main(results)
  File "/usr/sbin/dduper", line 595, in main
    dedupe_dir(results.dir_path, results.dry_run, results.recurse)
  File "/usr/sbin/dduper", line 571, in dedupe_dir
    populate_records(file_list)
  File "/usr/sbin/dduper", line 549, in populate_records
    btrfs_dump_csum(fn)
  File "/usr/sbin/dduper", line 269, in btrfs_dump_csum
    out, ret = check_btrfs_file_exists(filename)
  File "/usr/sbin/dduper", line 252, in check_btrfs_file_exists
    cursor.execute("SELECT * FROM filehash WHERE filename = ?",(filename,))
UnicodeEncodeError: 'utf-8' codec can't encode characters in position 58-59: surrogates not allowed
```

(I'm not sure if it's the same core issue as in #15 , so I file this one separately. Please feel free to move it there and/or mark as duplicate.)

**Comment by bobpaul** [comment]
I have dduper `v0.04.r23.g11b7855-1` installed (archlinux, [aur package](https://aur.archlinux.org/packages/dduper-git).

```
sudo dduper -p /dev/bcache3 -r -d /mnt/home /home/ -a
Traceback (most recent call last):                                                                                    
  File "/usr/bin/dduper", line 716, in <module>                                                                       
    main(results)                                                                                                     
  File "/usr/bin/dduper", line 596, in main                                                                           
    dedupe_dir(results.dir_path, results.dry_run, results.recurse)                                                    
  File "/usr/bin/dduper", line 572, in dedupe_dir                                                                     
    populate_records(file_list)                                                                                       
  File "/usr/bin/dduper", line 550, in populate_records                                                               
    btrfs_dump_csum(fn)                                                                                               
  File "/usr/bin/dduper", line 270, in btrfs_dump_csum                                                                
    out, ret = check_btrfs_file_exists(filename)                                                                      
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                      
  File "/usr/bin/dduper", line 253, in check_btrfs_file_exists                                                        
    cursor.execute("SELECT * FROM filehash WHERE filename = ?",(filename,))                                           
UnicodeEncodeError: 'utf-8' codec can't encode character '\udcd1' in position 83: surrogates not allowed
```
I'm not sure what's needed to prevent `filename` from getting converted to UTF-8. Maybe `cursor.execute(b"SELECT * FROM filehash WHERE filename = ?",(filename,))`? But maybe you need to set [text_factory to bytes](https://docs.python.org/3/library/sqlite3.html#sqlite3.Connection.text_factory)

Filenames on linux aren't required to be unicode and may include control characters and non-text characters.

I located the filename. in bash, `ls` displays it as `ESPA'$'\321''OL.CWK'`
