### ISSUE TITLE
AssertionError on very small dir

### ISSUE THREAD

**Issue by TheChief5055** [Lakshmipathi/dduper#69]
strace -o /mnt/logs.txt dduper --device  /dev/mapper/cachedev_0 --dir /mnt/Exchange --analyze --recurse
Traceback (most recent call last):
  File "/usr/sbin/dduper", line 575, in <module>
    main(results)
  File "/usr/sbin/dduper", line 465, in main
    dedupe_dir(results.dir_path, results.dry_run, results.recurse)
  File "/usr/sbin/dduper", line 456, in dedupe_dir
    dedupe_files(file_list, dry_run)
  File "/usr/sbin/dduper", line 410, in dedupe_files
    ret = do_dedupe(src_file, dst_file, dry_run)
  File "/usr/sbin/dduper", line 224, in do_dedupe
    assert len(out1) != 0
AssertionError

Strace log attached.

[logs.txt](https://github.com/Lakshmipathi/dduper/files/10502298/logs.txt)

**Comment by bugsyb** [comment]
Running into the same:
```
Traceback (most recent call last):
  File "/usr/local/sbin/dduper", line 734, in <module>
    main(results)
  File "/usr/local/sbin/dduper", line 595, in main
    dedupe_dir(results.dir_path, results.dry_run, results.recurse)
  File "/usr/local/sbin/dduper", line 578, in dedupe_dir
    dedupe_files(f, dry_run)
  File "/usr/local/sbin/dduper", line 482, in dedupe_files
    ret = do_dedupe(src_file, dst_file, dry_run)
  File "/usr/local/sbin/dduper", line 293, in do_dedupe
    assert len(out1) != 0
AssertionError
```

Tried running it in container as privileged, mapped device as well as directly at host level - same error.
It is aarch64.

```
DEBUG:root:Phase-1: Validating files and creating DB
DEBUG:root:Phase-1.1: Populate records using threads
DEBUG:root:Phase-2: Detecting duplicate files
DEBUG:root:Duplicate files are:
DEBUG:root:[['/mnt/storage-btrfs/dduper-test/storage.tgz', '/mnt/storage-btrfs/dduper-test/1/storage.tgz', '/mnt/storage-btrfs/dduper-test/2/storage.tgz']]
DEBUG:root:Phase-3: Dedupe duplicate files
DEBUG:root:['/mnt/storage-btrfs/dduper-test/storage.tgz', '/mnt/storage-btrfs/dduper-test/1/storage.tgz', '/mnt/storage-btrfs/dduper-test/2/storage.tgz']
DEBUG:root:Phase-1: Validating files and creating DB
DEBUG:root:Phase-1.1: Populate records using threads
DEBUG:root:Phase-2: Detecting duplicate files
DEBUG:root:Duplicate files are:
DEBUG:root:[['/mnt/storage-btrfs/dduper-test/storage.tgz', '/mnt/storage-btrfs/dduper-test/1/storage.tgz', '/mnt/storage-btrfs/dduper-test/2/storage.tgz']]
DEBUG:root:Phase-3: Dedupe duplicate files
DEBUG:root:['/mnt/storage-btrfs/dduper-test/storage.tgz', '/mnt/storage-btrfs/dduper-test/1/storage.tgz', '/mnt/storage-btrfs/dduper-test/2/storage.tgz']
```

**Comment by kotenok2000** [comment]
@bugsyb you didn't wait untill file finished uploading.

Here is my log

[strace.log](https://github.com/user-attachments/files/18906339/strace.log)

**Comment by bugsyb** [comment]
The file ends with:
```
munmap(0x7f1898187000, 33554432)        = 0
munmap(0x7f1896187000, 33554432)        = 0
exit_group(1)                           = ?
+++ exited with 1 +++
```

Unsure, why would the upload not be finished? Would you mind to expand on this?

**Comment by kotenok2000** [comment]
I think back in the day Github didn't block pressing of "Comment" button while upload was in progress.
So you could press ctrl+v and immediately press "comment", interrupting upload.
Looks like Github fixed this.
